# This file was generated by GoReleaser. DO NOT EDIT.
cask "flagsmith" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "baf9600d1760e33cf4adb30e9e3b1ec6bafe75350f70d776234bbaed7dea3ed7"
      url "https://github.com/Flagsmith/flagsmith-cli/releases/download/v#{version}/flagsmith_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e20a8318b783781fdb36fd50740e47f203444baecae569f4f206c22c4042ad2f"
      url "https://github.com/Flagsmith/flagsmith-cli/releases/download/v#{version}/flagsmith_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f7cf6f67682b369dbb33c6f7a11e5edb558397b26852409c46f931236aed179"
      url "https://github.com/Flagsmith/flagsmith-cli/releases/download/v#{version}/flagsmith_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a32cccda31558854b648623fdaf3a6429dc7e0f7bf0da53c9802a1f64eb21645"
      url "https://github.com/Flagsmith/flagsmith-cli/releases/download/v#{version}/flagsmith_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flagsmith"
  desc "The Flagsmith command-line interface"
  homepage "https://github.com/Flagsmith/flagsmith-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flagsmith"

  preflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flagsmith"]
    end
  end
  generate_completions_from_executable "flagsmith",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
